### PR TITLE
Add missing export symbol and suppress dll-interface warnings for MSVC 

### PR DESCRIPTION
**Pull request by panosk**
MSVC was complaining about this free function and wouldn't link the library with the clients. 

There were also countless dll-interface warnings which were polluting the compilation output. See also here: 
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4251?view=msvc-160
My understanding is that all these messages are related to STL-derived types in various places.

### CODE REVIEW

**Comment by guillaumekln** [comment]
Thanks! Could you rebase the branch on master?

**Comment by panosk** [comment]
Hm, I messed up rebasing. Can you help, or should I just ditch this PR and send a new one?

**Comment by guillaumekln** [comment]
Can you try cherry-picking the commit onto your branch?

```bash
git checkout add-missing-export-symbol
git cherry-pick d41f03512b1f0692f49fdb0e881828629c4a3e61
```

**Comment by panosk** [comment]
Thanks! Will try a bit later once I get back my Win laptop where I've made the changes. The mess probably happened because I created this branch from yesterday's branch `fix-sp-flags-for-msvc` which I deleted from my fork, and not from my rebased `master`...

**Comment by panosk** [comment]
Success, thank you!

**Comment by guillaumekln** [comment]
Thanks. I will look to add a Windows job in the CI to avoid these errors in the future.

**Pull request merged**
